POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpZCI6IjVjNjg5ZTFlZWRhZDEzNGMzZGI4MmE0NiIsImlhdCI6MTU1MDM2Nzc5NX0.LfWd-pmSwoKnB0H1vArtt9eKHE2C6QQuo8wmoS_rNDs

{
  "title": "title6",
  "author": "author6",
  "url": "url6",
  "likes": 6
}

###
